### ISSUE TITLE
Error When do the refresh and press back

### ISSUE THREAD

**Issue by shanmarkus** [gontovnik/DGElasticPullToRefresh#12]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x12e95fc00 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x12fc63f10> (
<NSKeyValueObservance 0x12fc34920: Observer: 0x12fc5ada0, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x12f915730>
)'

already did the de init :(

**Comment by shanmarkus** [comment]
found the solution !

just add 

override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
        self.tableView.dg_stopLoading()
    }

to stop the loading. Cheers.

**Comment by shanmarkus** [comment]
Observer: 0x160359d20, Key path: contentInset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x15efab460>

it seems the contentInset that cause the problem

**Comment by gontovnik** [comment]
I think this issue is related to #5, isn't it?

**Comment by shanmarkus** [comment]
found the quick hack however, it still cause an error sometimes

```
override func viewWillDisappear(animated: Bool) {
self.tableView.dg_stopLoading()
super.viewWillDisappear(animated)
}
```

**Comment by shanmarkus** [comment]
@gontovnik i found the solution :+1: Thanks Btw.

**Comment by gontovnik** [comment]
Thank you :+1:
