### ISSUE TITLE
UITableViews set via IBOutlets from xib, with tableHeaderView disappear after refresh

### ISSUE THREAD

**Issue by fraserscottmorrison** [gontovnik/DGElasticPullToRefresh#14]
If a UITableView is set in a xib file and hooked unto the view controller via an IBOutlet, and it includes a tableHeaderView, it disappears after a pull to refresh.

This will be because the IBOutlet only has a weak reference to the UITableView and it is removed from the view heirachy temporarily

This is where is occurs:
```swift
public extension UIScrollView {
    func dg_stopScrollingAnimation() {
        if let superview = self.superview, let index = superview.subviews.indexOf({ $0 == self }) as Int! {
            let strongSelf = self
            //removeFromSuperview() // commenting out this line fixes the issue, but Im not sure if its needed for something else (changing the index?)
            superview.insertSubview(strongSelf, atIndex: index)
        }
    }
}
```

**Comment by gontovnik** [comment]
Hi there. I am aware of this issue, have a look at: #1

**Comment by fraserscottmorrison** [comment]
Ah I see, I scanned the issue titles, but didn't think it'd been raised
