### ISSUE TITLE
Goes under UINavigation Bar

### ISSUE THREAD

**Issue by bobm77** [gontovnik/DGElasticPullToRefresh#17]
makes the tableView go under the UINavigation bar.

Here is the code I used to set up the pull to refresh.

// Initialize tableView
        let loadingView = DGElasticPullToRefreshLoadingViewCircle()
        loadingView.tintColor = UIColor.whiteColor()
        tableView.dg_addPullToRefreshWithActionHandler({ [weak self] () -> Void in
            self!.loadData()
            }, loadingView: loadingView)
        tableView.dg_setPullToRefreshFillColor(UIColor(red:0.000000, green:0.764706, blue:0.235294, alpha:1.0))
        tableView.dg_setPullToRefreshBackgroundColor(tableView.backgroundColor!)

![image](https://cloud.githubusercontent.com/assets/9518504/12016185/32fedcd0-ad05-11e5-951d-143e99c5d6cd.png)

![image](https://cloud.githubusercontent.com/assets/9518504/12016203/818198ac-ad05-11e5-879c-9f9d422f3349.png)

**Comment by gontovnik** [comment]
Could you please have a look, and tell whether test app works properly on your device? 
Do you disable content inset adjustment? Or any other viewController properties which could affect that?

**Comment by bobm77** [comment]
It was working fine and then it just stoped working. if I remove the code my table view works fine.
And yes the example works fine on my device

**Comment by bobm77** [comment]
And now it is randomly fixed with out me changing anything.

**Comment by gontovnik** [comment]
Awesome! :+1:
