### ISSUE TITLE
DGElasticPullToRefresh in Objective-C

### ISSUE THREAD

**Issue by Mainstayz** [gontovnik/DGElasticPullToRefresh#19]
I wrote a version for DGElasticPullToRefresh in Objective-C，but is imperfect , need your help
link :https://github.com/Mainstayz/DGElasticPullToRefresh 😊

**Comment by Easyzhan** [comment]
where imperfect？

**Comment by Mainstayz** [comment]
I have to set extendedLayoutIncludesOpaqueBars to yes in viewDidLoad(), otherwise DGElasticPullToRefresh doesn't work properly.

```
self.extendedLayoutIncludesOpaqueBars = YES;

```

**Comment by gontovnik** [comment]
Have a look at my implementation and try to write the same code but just in ObjC :+1:
