### ISSUE TITLE
DGElasticPullToRefreshLoadingViewCircle not public

### ISSUE THREAD

**Issue by tapz** [gontovnik/DGElasticPullToRefresh#2]
DGElasticPullToRefreshLoadingViewCircle is not public and is not accessible when using DGE as a framework (CocoaPods).

Also, please consider renaming the classes to have shorter names. Swift has namespaces, so no need to obj-c style long names and prefixes.

**Comment by gontovnik** [comment]
Hm. Do you have any thoughts why LoadingViewCircle is not accessible when using as a Framework?

Ok, I will re-think naming.

**Comment by tapz** [comment]
That's how it is in Swift. Internal classes are internal to a framework. Just make the classes and it's subclass public. Also all initializers and overriden methods.

**Comment by tapz** [comment]
The extension has to be public too.

**Comment by gontovnik** [comment]
Basically make all my classes, extension and etc:
public class..
public extension..
public struct..

Right?

**Comment by tapz** [comment]
Yes

**Comment by jyounus** [comment]
Was about to report the same issue with Cocoapods. 

Thanks in advance for fixing this!

**Comment by gontovnik** [comment]
Will make all public tonight and will push it

**Comment by carsonperrotti** [comment]
Any update on this? I would love to use it in a project.

**Comment by gontovnik** [comment]
Have a look at my latest commit on cocoapods branch: https://github.com/gontovnik/DGElasticPullToRefresh/tree/cocoapods

Is it enough for CocoaPods?

**Comment by tapz** [comment]
You need to make the default initializer public as well:

DGElasticPullToRefreshLoadingViewCircle:
65: init() {

**Comment by gontovnik** [comment]
What about extension methods such as:
func dg_addPullToRefreshWithActionHandler...?

**Comment by jyounus** [comment]
Might as well make it public. No harm in this case.

**Comment by gontovnik** [comment]
I guess now should be fine? :) If yes then I gonna merge it back to master and update cocoapods

**Comment by tapz** [comment]
Seems to work. Looks like the extension functions don't need to be public as long as the extension itself is public. But no harm in making them public.

Have to say that this is the most coolest looking pull to refresh control I have seen so far. Keep up the good work!

**Comment by tapz** [comment]
Looks like all files were not recompiled in my computer and there are still some problems. In the DGElasticPullToRefreshLoadingViewCircle class the init needs override keyword and setPullProgress, startAnimating and stopLoading need to be public as the overriden functions are public.

init(frame: .zero) does not compile. I think init() without frame should work as the base class already calls UIView's init with a zero frame.

**Comment by gontovnik** [comment]
Released version 1.0.2, check it out, now all should be public. Please let me know if something does not work for you.
