### ISSUE TITLE
Crash if the table view is removed before animation completes

### ISSUE THREAD

**Issue by joe528** [gontovnik/DGElasticPullToRefresh#22]
Need to add 

    if (!self.observing) { return } 

in animateBounce() -> UIView.animateWithDuration -> completion:

or it will cause crash if the tableview is removed before it's called.

**Comment by gontovnik** [comment]
Hey @joe528! Please feel free to add that and do pull-request. Will appreciate that!

**Comment by shinoys222** [comment]
@joe528 Pushed a commit as you said. It is working fine for now. Thanks
