### ISSUE TITLE
Refreshing makes the UITableView disappear

### ISSUE THREAD

**Issue by BalestraPatrick** [gontovnik/DGElasticPullToRefresh#24]
Hello,

The animation looks amazing but I can't get it to work. This is my code:
```swift
let loadingView = DGElasticPullToRefreshLoadingViewCircle()
loadingView.tintColor = UIColor.whiteColor()
tableView.dg_addPullToRefreshWithActionHandler({ [weak self] in
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(1.5 * Double(NSEC_PER_SEC))), dispatch_get_main_queue(), {
            self?.tableView.dg_stopLoading()
        })
        }, loadingView: loadingView)
tableView.dg_setPullToRefreshFillColor(UIColor().menuDarkBlueColor())
tableView.dg_setPullToRefreshBackgroundColor(view.backgroundColor!)
```
Even if I remove the `dispatch_after`, as soon as I release the UIScrollView of the tableView, it completely disappears from the hierarchy. As you can see from these screenshots, the UITableView is removed from the hierarchy. Could this be due to a bug in your library?
The first screenshot is before reloading, the second one is while the pull to refresh animation is in course and the last is when the UIScrollView is released. You can find my source code here: https://github.com/BalestraPatrick/Tweetometer
**First**
![screen shot 2016-02-10 at 8 54 36 pm](https://cloud.githubusercontent.com/assets/3658887/12960052/786b0738-d039-11e5-8c7c-91c314715495.png)
**Second**
![screen shot 2016-02-10 at 8 54 52 pm](https://cloud.githubusercontent.com/assets/3658887/12960055/7a8d9256-d039-11e5-915b-1c9d7eef65b3.png)
**Third**
![screen shot 2016-02-10 at 8 55 02 pm](https://cloud.githubusercontent.com/assets/3658887/12960057/7c6a6810-d039-11e5-87d6-07a674b06996.png)

**Comment by gontovnik** [comment]
Hello,

Are you doing your layout in code or you are using storyboard and constraints?

**Comment by BalestraPatrick** [comment]
I'm using Storyboard to set up my UITableView.

**Comment by gontovnik** [comment]
Then you can have a look at issue #1, people were facing the same issue. It was happening because of my implementation "force stop scrolling animation". I think this function is not needed anymore and we can get rid of that. I will try to test it more this weekend and update pod.
