### ISSUE TITLE
Don't work if CollectionView is empty

### ISSUE THREAD

**Issue by SpectralDragon** [gontovnik/DGElasticPullToRefresh#37]
I'm create my collectionView in `loadView()` method, and if my collection is empty i can't refresh him. What happened? :)

**Comment by rottajuliano** [comment]
Are you using **DZNEmptyDataSet**? It wasn't working for me as well. I found out it was a conflict with DZNEmptyDataSet, which disables scroll. You should add this to the bottom of your view controller to make it work.

```
extension NameOfTheCollectionViewController: DZNEmptyDataSetSource, DZNEmptyDataSetDelegate
{
    func emptyDataSetShouldAllowScroll(scrollView: UIScrollView!) -> Bool {
        return true
    }
}
```

Hope it helps. Cheers

**Comment by chindoo** [comment]
I have the same problem i can not refresh the collectionView when it is empty.
I tried using DZNEmptyDataSet even though it is not mentioned in the wiki but no luck.

**Comment by Omeesh** [comment]
This worked for me...

**self.collectionView.alwaysBounceVertical = true**

**Comment by SpectralDragon** [comment]
@Omeesh  thanks you!)

**Comment by tounaobun** [comment]
Aha... good job.

**Comment by MuseerAnsari** [comment]
@Omeesh thank you :)

**Comment by rejsiperpalaj** [comment]
@Omeesh ;) thanks bro
