### ISSUE TITLE
Not working on Xcode 8 / Swift 3

### ISSUE THREAD

**Issue by ghost** [gontovnik/DGElasticPullToRefresh#52]
I installed DGElasticPullToRefresh using cocoapod. So I have version (1.0.3).
It does not build : I have 30 errors.

Is swift 3 support planned ?

Many thanks

**Comment by prettysunflower** [comment]
Have you try this :
pod "DGElasticPullToRefresh", :git => 'https://github.com/gontovnik/DGElasticPullToRefresh.git'

**Comment by gontovnik** [comment]
You should try version 1.1 instead of 1.0.3. 

Thanks

**Comment by ghost** [comment]
How do I try version 1.1 ?
I just configured: pod "DGElasticPullToRefresh" 

Do You mean: 
pod 'DGElasticPullToRefresh', '~> 1.1'
