### ISSUE TITLE
UITableView flicker

### ISSUE THREAD

**Issue by aamahdwalker** [gontovnik/DGElasticPullToRefresh#84]
Experiencing bug on iPhoneX only. Cannot reproduce in simulator. When I let go of pull, the tableView quickly snaps to the top of the view and then readjusts to proper position under navigation bar.

**Comment by ren6** [comment]
@aamahdwalker I have the same issue. How did you fix it?

**Comment by ren6** [comment]
Okay, I fixed it like this. In DGElasticPullToRefreshView.swift inside displayLinkTick() method I changed this:
```
scrollView.contentInset.top = bounceAnimationHelperView.dg_center(isAnimating()).y
scrollView.contentOffset.y = -scrollView.contentInset.top
```
to this:
```
let oldValue = scrollView.contentInset.top
let newValue = bounceAnimationHelperView.dg_center(isAnimating()).y
if oldValue > newValue && oldValue > 0 && (newValue == 0 || newValue == DGElasticPullToRefreshConstants.LoadingContentInset) && oldValue - newValue > DGElasticPullToRefreshConstants.LoadingContentInset {
  print("SKIP STRANGE INSET CHANGING: from \(oldValue) to \(newValue)")
} else {
   scrollView.contentInset.top = newValue
   scrollView.contentOffset.y = -scrollView.contentInset.top
}
```

**Comment by aamahdwalker** [comment]
@ren6 Nice! Another fix is to add lines 301-302 in animation block like so..  

      [UIView animateWithDuration:0.1 animations:^{
            scrollView.contentInset = contentInset;
        }
                         completion:^(BOOL finished) {
                             completionBlock();
                         }];
    }
